config/routes.rb
Leido::Application.routes.draw do
  devise_for :users

  resources :links

  get "links/index"

  root :to => "links#index"
  

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :presence => true
  validates :title, :presence => true
  
  validates_uniqueness_of :url, :case_sensitive => false
  
  belongs_to :user
  
  acts_as_voteable
  
  named_scope :descending, :order => "created_at DESC"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :login, :password, :password_confirmation, :remember_me
  
  # To allow for authenticating via username or email
  attr_accessor :login
  
  # For vote_fu
  acts_as_voter
  
  protected
  def self.find_for_database_authentication(conditions)
    login = conditions.delete(:login)
    where(conditions).where(["username = :value OR email = :value", { :value => login}]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /links
  # GET /links.xml
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end

  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])
    @link.user = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to(@link, :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to(@link, :notice => 'Link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end  
  
end

app/controllers/votes_controller.rb
# An example controller for "votes" that are nested resources under users. See examples/routes.rb

class VotesController < ApplicationController

  # First, figure out our nested scope. User or Voteable? 
  before_filter :find_votes_for_my_scope, :only => [:index]
     
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :must_own_vote,  :only => [:edit, :destroy, :update]
  before_filter :not_allowed,    :only => [:edit, :update, :new]

  # GET /users/:user_id/votes/
  # GET /users/:user_id/votes.xml
  # GET /users/:user_id/voteables/:voteable_id/votes/
  # GET /users/:user_id/voteables/:voteable_id/votes.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @votes }
    end
  end

  # GET /users/:user_id/votes/1
  # GET /users/:user_id/votes/1.xml
  # GET /users/:user_id/voteables/:voteable_id/votes/1
  # GET /users/:user_id/voteables/:voteable_id/1.xml
  def show
    @voteable = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  # GET /users/:id/votes/new      
  # GET /users/:id/votes/new.xml  
  # GET /users/:id/votes/new      
  # GET /users/:id/votes/new.xml  
  def new
    # Not generally used. Most people want to vote via AJAX calls.
  end

  # GET /users/:id/votes/1/edit
  def edit
    # Not generally used. Most people don't want to allow editing of votes.
  end

  # POST /users/:user_id/voteables/:voteable_id/votes
  # POST /users/:user_id/voteables/:voteable_id/votes.xml
  def create
    @link = Link.find(params[:quote_id])
    
    respond_to do |format|
      if current_user.vote(@link, params[:vote])
        format.rjs  { render :action => "create", :vote => @vote }
        format.html { redirect_to([@link.user, @link]) }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.rjs  { render :action => "error" }
        format.html { render :action => "new" }
        format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/:id/votes/1
  # PUT /users/:id/votes/1.xml
  def update
    # Not generally used
  end
  
  # DELETE /users/:id/votes/1
  # DELETE /users/:id/votes/1.xml
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to(user_votes_url) }
      format.xml  { head :ok }
    end
  end

  private
  def find_votes_for_my_scope
    if params[:voteable_id]
      @votes = Vote.for_voteable(Voteable.find(params[:voteable_id])).descending
    elsif params[:user_id]
      @votes = Vote.for_voter(User.find(params[:user_id])).descending         
    else  
      @votes = []
    end
  end

  def must_own_vote
    @vote ||= Vote.find(params[:id])
    @vote.user == current_user || ownership_violation
  end

  def ownership_violation
    respond_to do |format|
      flash[:notice] = 'You cannot edit or delete votes that you do not own!'
      format.html do
        redirect_to user_path(current_user)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/index.html.erb
<h1>Le&iacute;do</h1>


<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% unless @links.nil? %>
<%  @links.each do |link| %>
  <tr>
    <td><%= link.url %></td>
    <td><%= link.title %></td>
    <td><%= link.description %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<%  end %>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leido</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="user_nav">  
   <% if user_signed_in? %>  
     Signed in as <%= current_user.username %>. Not you?  
     <%= link_to "Sign out", destroy_user_session_path %>  
   <% else %>  
     <%= link_to "Sign up", new_user_registration_path %> or  
     <%= link_to "Sign in", new_user_session_path %>  
   <% end %>  
</div>  
   
<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_link_vote.html.erb
<% 
	# You can't vote if it is your link, 
	# you are not logged in, 
	# or you have already voted on it
	
	unless link.user == current_user ||
	!logged_in? ||
	current_user.voted_on?(@link)
%>

	<%= link_to_remote "Up", 
		:url => user_link_votes_path(link.user, link, :vote => :true, :format => :rjs), 
		:method => :post
	%> 
	/
	<%= link_to_remote "Down", 
		:url => user_link_votes_path(link.user, link, :vote => :false, :format => :rjs), 
		:method => :post
 	%> 

<% end %>

<b>Votes:</b> <%= link.votes_for - link.votes_against %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>

	
  <tr>
  <td>
    <td><%= link.url %></td>
    <td><%= link.title %></td>
    <td><%= link.description %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<div id="link_<%= @link.id %>">
	<div id="votes_<%= @link.id %>">
		<%= render :partial => "link_vote", :locals => {:link => @link} %>
	</div>
  
<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Title:</b>
  <%= @link.title %>
</p>

<p>
  <b>Description:</b>
  <%= @link.description %>
</p>

<p>
  <b>Submitter:</b>
  <%= @link.user.username  %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>